const {Properties} = require("../models");

const propertiesData = [
    {
        number_of_bedrooms:3,
        number_of_bathrooms: 2.5,
        property_type: "Townhome",
        square_footage:2500,
        year_built:2018,
        location_address:"1477 White River Way",
        location_city:"Provo",
        location_state:"UT",
        zip_code:84660,
        parking_type:"Parking Garage",
        parking_spaces:2,
        homeowners_association:"Yes",
        hoa_fee:145,
        utilities:"Water, Gas",
        rent_amount:1800

    },
    {
        number_of_bedrooms:5,
        number_of_bathrooms: 4.5,
        property_type:"Single Family Home",
        square_footage:2500,
        year_built:2018,
        location_address:"1878 E 1050 S",
        location_city:"Spanish Fork",
        location_state:"UT",
        zip_code:84661,
        parking_type:"Parking Garage",
        parking_spaces:3,
        homeowners_association:"No",
        hoa_fee:0,
        utilities:"Water",
        rent_amount:3400

    },
    {
        number_of_bedrooms:1,
        number_of_bathrooms:1.5, 
        property_type:"Condo",
        square_footage:1200,
        year_built:2020,
        location_address:"43 N 900 W",
        location_city:"Provo",
        location_state:"UT",
        zip_code:84604,
        parking_type:"Parking Stall",
        parking_spaces:2,
        homeowners_association:"Yes",
        hoa_fee:50,
        utilities:"Water, Gas",
        rent_amount:1325

    },
    {
        number_of_bedrooms:1,
        number_of_bathrooms:1,
        property_type:"Condo",
        square_footage:1250,
        year_built:2020,
        location_address:"1193 N 1400 W",
        location_city:"Provo",
        location_state:"UT",
        zip_code:84604,
        parking_type:"Parking Stall",
        parking_spaces:2,
        homeowners_association:"Yes",
        hoa_fee:25,
        utilities:"Electric",
        rent_amount:1200

    },
    {
        number_of_bedrooms:4,
        number_of_bathrooms:2.5,
        property_type:"Townhome",
        square_footage:2400,
        year_built:2018,
        location_address:"502 S 1040 E Apt 228",
        location_city:"American Fork",
        location_state:"UT",
        zip_code:84003,
        parking_type:"Parking Garage",
        parking_spaces:1,
        homeowners_association:"Yes",
        hoa_fee:200,
        utilities:"Water, Elecrtic",
        rent_amount:1850

    },
    {
        number_of_bedrooms:3,
        number_of_bathrooms:2.5,
        property_type:"Townhome",
        square_footage:2150,
        year_built:2018,
        location_address:"1877 W Pointe Meadow Loop",
        location_city:"Lehi",
        location_state:"UT",
        zip_code:84043,
        parking_type:"Parking Garage",
        parking_spaces:2,
        homeowners_association:"Yes",
        hoa_fee:250,
        utilities:"Water, Electric, Gas",
        rent_amount:1300

    },
    {
        number_of_bedrooms:3,
        number_of_bathrooms: 2.5,
        property_type:"Single Family Home",
        square_footage:3200,
        year_built:2011,
        location_address:"2000 N, 300 South",
        location_city:"Lehi",
        location_state:"UT",
        zip_code:84043,
        parking_type:"Parking Garage",
        parking_spaces:2,
        homeowners_association:"Yes",
        hoa_fee:200,
        utilities:"Gas, Electric",
        rent_amount:2600

    },
    {
        number_of_bedrooms:3,
        number_of_bathrooms: 3.5,
        property_type:"Condo",
        square_footage:1050,
        year_built:2018,
        location_address:"2396 W 510 N",
        location_city:"Salem",
        location_state:"UT",
        zip_code:84601,
        parking_type:"Parking Garage",
        parking_spaces:2,
        homeowners_association:"Yes",
        hoa_fee:125,
        utilities:"Gas",
        rent_amount:2100

    },
    {
        number_of_bedrooms:2,
        number_of_bathrooms:2.5,
        property_type:"Townhome",
        square_footage:1994,
        year_built:2012,
        location_address: "1428 E 80 S",
        location_city:"Lindon",
        location_state:"UT",
        zip_code:84663,
        parking_type:"Parking Garage",
        parking_spaces:2,
        homeowners_association:"Yes",
        hoa_fee:100,
        utilities:"Electric",
        rent_amount:1350

    },
    {
        number_of_bedrooms:2,
        number_of_bathrooms:1, 
        property_type:"Condo",
        square_footage:1785,    
        year_built:2012,
        location_address: "766 N 200 E",
        location_city:"Springville",
        location_state:"UT",
        zip_code:84664,
        parking_type:"Parking Stall",
        parking_spaces:1,
        homeowners_association:"Yes",
        hoa_fee:25,
        utilities:"Gas, Electric",
        rent_amount:800

    },
    {
        number_of_bedrooms:2,
        number_of_bathrooms:1.5, 
        property_type:"Condo",
        square_footage:1930,
        year_built:1999,
        location_address:"341 S Churchill St Unit 102",
        location_city:"Lindon",
        location_state:"UT",
        zip_code:84653,
        parking_type:"Parking Stall",
        parking_spaces:2,
        homeowners_association:"Yes",
        hoa_fee:25,
        utilities:"Water",
        rent_amount:950

    },
    {
        number_of_bedrooms:1,
        number_of_bathrooms:1, 
        property_type:"Condo",
        square_footage:1130,
        year_built:2020,
        location_address:"372 E 960 S",
        location_city:"Mapleton",
        location_state:"UT",
        zip_code:84062,
        parking_type:"Parking Stall",
        parking_spaces:2,
        homeowners_association:"Yes",
        hoa_fee:50,
        utilities:"Water, Gas, Electric",
        rent_amount:1200

    },
    {
        number_of_bedrooms:3,
        number_of_bathrooms:2.5, 
        property_type:"Townhome",
        square_footage:1500,
        year_built:2019,
        location_address:"85 N Spencer Rd",
        location_city:"Salem",
        location_state:"UT",
        zip_code:84043,
        parking_type:"Parking Garage",
        parking_spaces:1,
        homeowners_association:"Yes",
        hoa_fee:100,
        utilities:"Water, Gas, Electric",
        rent_amount:2450

    },
    {
        number_of_bedrooms:3,
        number_of_bathrooms:2, 
        property_type:"Townhome",
        square_footage:1894,
        year_built:2019,
        location_address:"2297 W Cresthaven Ln N Unit 21",
        location_city:"Pleasant Grove",
        location_state:"UT",
        zip_code:84057,
        parking_type:"Parking Garage",
        parking_spaces:2,
        homeowners_association:"Yes",
        hoa_fee:150,
        utilities:"Water",
        rent_amount:2000

    },
    {
        number_of_bedrooms:3,
        number_of_bathrooms:3.5,
        property_type:"Townhome",
        square_footage:2875,
        year_built:2021,
        location_address:"454 W 1010 N",
        location_city:"Lehi",
        location_state:"UT",
        zip_code:84043,
        parking_type:"Parking Stall",
        parking_spaces:2,
        homeowners_association:"Yes",
        hoa_fee:125,
        utilities:"Water, Gas, Electric",
        rent_amount:1200

    },
    {
        number_of_bedrooms:3,
        number_of_bathrooms:2, 
        property_type:"Single Family Home",
        square_footage:2498,
        year_built:2021,
        location_address: "2349 N 1100 E",
        location_city:"Orem",
        location_state:"UT",
        zip_code:84043,
        parking_type:"Parking Garage",
        parking_spaces:3,
        homeowners_association:"No",
        hoa_fee:0,
        utilities:"Water, Gas, Electric",
        rent_amount:1200

    },
    {
        number_of_bedrooms:3,
        number_of_bathrooms:2.5, 
        property_type:"Single Family Home",
        square_footage:2424,
        year_built:2005,
        location_address:"2073 W Northridge Dr N Unit 10",
        location_city:"Lehi",
        location_state:"UT",
        zip_code:84043,
        parking_type:"Parking Garage",
        parking_spaces:3,
        homeowners_association:"No",
        hoa_fee:0,
        utilities:"Water, Gas, Electric",
        rent_amount:1550

    },
    {
        number_of_bedrooms:3,
        number_of_bathrooms:2, 
        property_type:"Single Family Home",
        square_footage:3224,
        year_built:1984,
        location_address:"120 W 3430 N",
        location_city:"Lehi",
        location_state:"UT",
        zip_code:84043,
        parking_type:"Parking Garage",
        parking_spaces:2,
        homeowners_association:"No",
        hoa_fee:0,
        utilities:"Water, Gas, Electric",
        rent_amount:1500

    },
    {
        number_of_bedrooms:3,
        number_of_bathrooms:3.5, 
        property_type:"Single Family Home",
        square_footage:2994,
        year_built:1988,
        location_address:"4308 W 1850 N Unit 201",
        location_city:"Lehi",
        location_state:"UT",
        zip_code:84043,
        parking_type:"Parking Garage",
        parking_spaces:3,
        homeowners_association:"No",
        hoa_fee:0,
        utilities:"Water, Gas, Electric",
        rent_amount:3500

    },
    {
        number_of_bedrooms:6,
        number_of_bathrooms:5.5, 
        property_type:"Single Family Home",
        square_footage:5500,
        year_built:2018,
        location_address:"1901 W Oakridge",
        location_city:"Orem",
        location_state:"UT",
        zip_code:84058,
        parking_type:"Parking Garage",
        parking_spaces:2,
        homeowners_association:"No",
        hoa_fee:0,
        utilities:"Water, Gas, Electric",
        rent_amount:2800

    },
    {
        number_of_bedrooms:5,
        number_of_bathrooms:2.5, 
        property_type:"Townhome",
        square_footage:3584,
        year_built:2010,
        location_address:"107 E Jordan Ridge Blvd Unit 512",
        location_city:"Saratoga Springs",
        location_state:"UT",
        zip_code:84045,
        parking_type:"Parking Stall",
        parking_spaces:2,
        homeowners_association:"Yes",
        hoa_fee:150,
        utilities:"Water",
        rent_amount:1600

    },
    {
        number_of_bedrooms:4,
        number_of_bathrooms:2.5, 
        property_type:"Single Family Home",
        square_footage:2120,
        year_built:2017,
        location_address:"320 E Pavilion Cir",
        location_city:"Saratoga Springs",
        location_state:"UT",
        zip_code:84045,
        parking_type:"Parking Garage",
        parking_spaces:2,
        homeowners_association:"No",
        hoa_fee:0,
        utilities:"Electric",
        rent_amount:1850

    },
    {
        number_of_bedrooms:3,
        number_of_bathrooms:1, 
        property_type:"Townhome",
        square_footage:1852,
        year_built:2014,
        location_address:"404 S 200 E",
        location_city:"American Fork",
        location_state:"UT",
        zip_code:84003,
        parking_type:"Parking Garage",
        parking_spaces:3,
        homeowners_association:"Yes",
        hoa_fee:300,
        utilities:"Water",
        rent_amount:1400

    },
    {
        number_of_bedrooms:3,
        number_of_bathrooms:1, 
        property_type:"Townhome",
        square_footage:1908,
        year_built:1999,
        location_address:"299 N 725 E",
        location_city:"Vineyard",
        location_state:"UT",
        zip_code:84059,
        parking_type:"Parking Stall",
        parking_spaces:1,
        homeowners_association:"Yes",
        hoa_fee:50,
        utilities:"Water",
        rent_amount:1400,

    },
    {
        number_of_bedrooms:2,
        number_of_bathrooms:1.5, 
        property_type:"Townhome",
        square_footage:1668,
        year_built:2000,
        location_address:"1588 E 1060 N",
        location_city:"Lehi",
        location_state:"UT",
        zip_code:84043,
        parking_type:"Parking Garage",
        parking_spaces:2,
        homeowners_association:"Yes",
        hoa_fee:150,
        utilities:"Water",
        rent_amount:1250

    },
    {
        number_of_bedrooms:2,
        number_of_bathrooms:1, 
        property_type:"Townhome",
        square_footage:4105,
        year_built:2008,
        location_address:"50 E Mountain Vale Way",
        location_city:"Woodland Hills",
        location_state:"UT",
        zip_code:84653,
        parking_type:"Parking Garage",
        parking_spaces:2,
        homeowners_association:"Yes",
        hoa_fee:180,
        utilities:"Water, Gas, Electric",
        rent_amount:1250

    },
    {
        number_of_bedrooms:2,
        number_of_bathrooms:1, 
        property_type:"Single Family Home",
        square_footage:2302,
        year_built:2019,
        location_address:"803 W 175 S",
        location_city:"Springville",
        location_state:"UT",
        zip_code:84663,
        parking_type:"Parking Garage",
        parking_spaces:3,
        homeowners_association:"No",
        hoa_fee:0,
        utilities:"Water, Gas, Electric",
        rent_amount:1700

    },
    {
        number_of_bedrooms:2,
        number_of_bathrooms:1.5, 
        property_type:"Condo",
        square_footage:824,
        year_built:2018,
        location_address:"1273 Riverside Ave Apt 5",
        location_city:"Saratoga Springs",
        location_state:"UT",
        zip_code:84604,
        parking_type:"Parking Stall",
        parking_spaces:3,
        homeowners_association:"Yes",
        hoa_fee:50,
        utilities:"Gas, Electric",
        rent_amount:1000,

    },
    {
        number_of_bedrooms:1,
        number_of_bathrooms:1, 
        property_type:"Single Family Home",
        square_footage:7040,
        year_built:2019,
        location_address:"1242 N 200 W",
        location_city:"Orem",
        location_state:"UT",
        zip_code:84057,
        parking_type:"Parking Garage",
        parking_spaces:2,
        homeowners_association:"No",
        hoa_fee:0,
        utilities:"Gas",
        rent_amount:1500

    },
    {
        number_of_bedrooms:3,
        number_of_bathrooms:1, 
        property_type:"Townhome",
        square_footage:2409,
        year_built:2020,
        location_address:"312 E Pavilion Cir",
        location_city:"Saratoga Springs",
        location_state:"UT",
        zip_code:84045,
        parking_type:"Parking Garage",
        parking_spaces:1,
        homeowners_association:"Yes",
        hoa_fee:150,
        utilities:"Water",
        rent_amount:1350

    },
    {
        number_of_bedrooms:3,
        number_of_bathrooms:2.5, 
        property_type:"Townhome",
        square_footage:7501,
        year_built:2020,
        location_address:"488 S Ponderosa Dr W",
        location_city:"Alpine",
        location_state:"UT",
        zip_code:84004,
        parking_type:"Parking Garage",
        parking_spaces:1,
        homeowners_association:"No",
        hoa_fee:0,
        utilities:"Water, Gas, Electric",
        rent_amount:1300

    },
    {
        number_of_bedrooms:3,
        number_of_bathrooms:3, 
        property_type:"Single Family Home",
        square_footage:9374,
        year_built:2019,
        location_address:"785 E Grove Dr N",
        location_city:"Alpine",
        location_state:"UT",
        zip_code:84004,
        parking_type:"Parking Garage",
        parking_spaces:2,
        homeowners_association:"No",
        hoa_fee:0,
        utilities:"Water, Gas, Electric",
        rent_amount:2500

    },
    {
        number_of_bedrooms:6,
        number_of_bathrooms:2.5, 
        property_type:"Single Family Home",
        square_footage:6900,
        year_built:2015,
        location_address:"455 Silver Leaf Dr",
        location_city:"Alpine",
        location_state:"UT",
        zip_code:84004,
        parking_type:"Parking Garage",
        parking_spaces:2,
        homeowners_association:"No",
        hoa_fee:0,
        utilities:"Water, Gas, Electric",
        rent_amount:1750

    },
    {
        number_of_bedrooms:5,
        number_of_bathrooms:4.5, 
        property_type:"Single Family Home",
        square_footage:4369,
        year_built:1978,
        location_address: "368 S 700 W",
        location_city:"Salem",
        location_state:"UT",
        zip_code:84601,
        parking_type:"Parking Garage",
        parking_spaces:2,
        homeowners_association:"No",
        hoa_fee:0,
        utilities:"Water, Gas, Electric",
        rent_amount:1300

    }
];

const seedProperties = () => Properties.bulkCreate(propertiesData);

module.exports = seedProperties;